name: wasm_test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: wasm integration tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pkg/client-sdk
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.23.1'

      - name: Run go work sync
        run: go work sync

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@v1

      - name: Start Docker services
        run: make -C ../.. docker-run

      - name: wasm test
        run: make test-wasm